dist:             trusty
sudo:             required
language:         php

addons:
  apt:
      packages:
        - parallel
  hosts:
    - govcms8.local

branches:
  only:
     # Only run Travis on major branches (1.x, 8.x-5.x etc) to avoid double builds
     - /^\d\.x(-\d\.x)?(-\S*)?$/

cache:
  bundler:        true
  apt:            true
  directories:
    - "$HOME/.composer/cache"

php:
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php:        7.2
  fast_finish:    true

before_install:
  # Tweak PHP configuration.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'max_execution_time = 180' >> govcms.php.ini;
  - echo 'sendmail_path = /bin/true' >> govcms.php.ini;
  - phpenv config-add govcms.php.ini
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv rehash

  # Composer
  - composer self-update
  - composer --version

  # Validate composer.json file.
  - composer validate composer.json --no-check-all --ansi --no-interaction

install:
  # Add Composer's local bin directory to the PATH.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Install GovCMS codes.
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer --verbose install

script:
  - ls -D $TRAVIS_BUILD_DIR
